services:
  salon-db:
    image: postgres:16
    container_name: salon-db
    environment:
      POSTGRES_USER: salon
      POSTGRES_PASSWORD: salon
      POSTGRES_DB: salon_db
    ports:
      - "5432:5432"
    volumes:
      - salon_db_data:/var/lib/postgresql/data

  portal-db:
    image: postgres:16
    container_name: portal-db
    environment:
      POSTGRES_USER: portal
      POSTGRES_PASSWORD: portal
      POSTGRES_DB: portal_db
    ports:
      - "5433:5432"
    volumes:
      - portal_db_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

volumes:
  salon_db_data:
  portal_db_data: